site_name: 深圳大学飞跃手册
repo_url: https://github.com/szu-feiyue/docs
edit_uri: edit/main/docs/
site_url: https://SZU-Aplication.github.io
site_author: SZU Feiyue Team
copyright: 'Copyright &copy; 2024 SZU Feiyue Team'

nav:
  - 首页:
    - index.md
    - 编写委员会: main/committee.md
    - 友链: main/friendlink.md
  - 留学:
    - liuxue/index.md
    - 基础知识: liuxue/basic.md
    - 2025届: 
      - 目录: liuxue/2025/index.md
      - 陈天行 - MMLab-HKU PhD@CS: liuxue/2025/cases/tianxingchen.md
      - 陈铭康 - HKU MSc@CS: liuxue/2025/cases/mingkangchen.md
      - 张硕 - NUS MSc@ECE: liuxue/2025/cases/shuozhang.md
    - 2024届: 
      - 目录: liuxue/2024/index.md
      - 李晓璐 - Maryland PhD@Stats: liuxue/2024/cases/xiaoluli.md
      - 秦言 - HKUST PhD@ECE: liuxue/2024/cases/yanqin.md
      - 王睿芃 - Upenn MS@CS: liuxue/2024/cases/ruipengwang.md
      - 忆如 - Edinburgh MS@CS: liuxue/2024/cases/wenli.md
      - 苏嘉淇 - HKU MSc@CS: liuxue/2024/cases/jiaqisu.md
      - Anthony - HKUSTgz MSc@CS: liuxue/2024/cases/zihaotang.md
      - 快乐摸鱼生活 - HKUST MSc@TLE: liuxue/2024/cases/yuanlan.md
      - 苏政欣 – Duke@MEM: liuxue/2024/cases/zhengxinsu.md
      - 陈同学 - UMacau@DS: liuxue/2024/cases/nuochen.md
    - 2022届: 
      - 目录: liuxue/2022/index.md
      - 彭镇灿 - Rutgers PhD@CS: liuxue/2022/cases/zhencanpeng.md
      - 詹卓欣 - SFU PhD@CS: liuxue/2022/cases/zhuoxinzhan.md
  - 保研:
    - baoyan/index.md
    - 基础知识: baoyan/basic.md
    - 2025届: 
      - 目录: baoyan/2025/index.md
      - 朱宇飞 - 上科大@CS: baoyan/2025/cases/yufeizhu.md
      - 钟昊天 - 浙大PhD@CS: baoyan/2025/cases/haotianzhong.md
      - 陈潇泳 - 北理工@CS: baoyan/2025/cases/xiaoyongchen.md
      - 李深艺 – 北大PhD@Matl: baoyan/2025/cases/shenyili.md
      - Mia - 东南@CS: baoyan/2025/cases/zhentingliao.md
      - 李林一 - 南开程明明组PhD@CS: baoyan/2025/cases/linyili.md
      - 张豪杰 - 深大PhD@CS: baoyan/2025/cases/haojiezhang.md
      - 王淇 - 南科大@Math: baoyan/2025/cases/qiwang.md
      - 陈婉纯 - 华南理工PhD@CS: baoyan/2025/cases/wanchunchen.md
    - 2024届: 
      - 目录: baoyan/2024/index.md
      - 苏梓瀚 - 清华深圳@CS: baoyan/2024/cases/zihansu.md
      - 梁霈柔 - 中科大@CS: baoyan/2024/cases/peirouliang.md
      - 汪贝琪 - 华科@CS: baoyan/2024/cases/beiqiwang.md
      - 陈耿 - 北邮@CS: baoyan/2024/cases/gengchen.md
      - 陈俊明 - 电科@CS: baoyan/2024/cases/junmingchen.md
      - 何志浩 - 上交PhD@CS: baoyan/2024/cases/zhihaohe.md
      - 刘涛 - 南开媒体计算实验室@CS: baoyan/2024/cases/taoliu.md
      - 郭奕彤 - 清华深圳@药学: baoyan/2024/cases/yitongguo.md
    - 2023届: 
      - 目录: baoyan/2023/index.md
      - 许宏浩 - 深大VCC优青组@CS: baoyan/2023/cases/honghaoxu.md
      - 曹弈轩 - 深大@CS: baoyan/2023/cases/yixuancao.md
      - ywh - 厦大MAC实验室@CS: baoyan/2023/cases/weihaoye.md
  - 考研:
    - kaoyan/index.md
    - 基础知识: kaoyan/basic.md
    - 2025届: 
      - 目录: kaoyan/2025/index.md
    - 2024届: 
      - 目录: kaoyan/2024/index.md
      - 颜治强 - 哈工深@CS: kaoyan/2024/cases/zhiqiangyan.md
  - 就业:
    - jiuye/index.md
    - 基础知识: jiuye/basic.md
    - 2026届: 
      - 目录: jiuye/2026/index.md
      - 关浩林 - Kasma实习: jiuye/2026/cases/haolinguan.md
    - 2025届: 
      - 目录: jiuye/2025/index.md
      - 李伟力 - 量化交易: jiuye/2025/cases/weilili.md
      - 陈梓淳 - 腾讯实习转正: jiuye/2025/cases/zichunchen.md
      - 李佳乐 - 腾讯实习转正: jiuye/2025/cases/jialeli.md
      - 闪闪 - 腾讯实习: jiuye/2025/cases/yaqinshan.md
      - 叶可禾 - 腾讯实习: jiuye/2025/cases/keheye.md
      - 刘逸飞 - 腾讯、字节、深信服实习: jiuye/2025/cases/yifeililu.md
    - 2024届: 
      - 目录: jiuye/2024/index.md
    - 2021届: 
      - 目录: jiuye/2021/index.md
      - debug君 - 深信服（已离职）+ 美团: jiuye/2021/cases/zehongluo.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - navigation.top
    - toc.follow
    - announce.dismiss
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: false

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized
  - add-number:
      strict_mode: False
      order: 2
  - git-authors:
      show_contribution: true
