site_name: 深圳大学飞跃手册
repo_url: https://github.com/szu-feiyue/docs
edit_uri: edit/main/docs/
site_url: https://SZU-Aplication.github.io
site_author: SZU Feiyue Team
copyright: 'Copyright &copy; 2024 SZU Feiyue Team'

nav:
  - 首页:
    - index.md
    - 编写委员会: main/committee.md
    - 友链: main/friendlink.md
  - 留学:
    - liuxue/index.md
    - 信息与技术工程类: 
      # - 目录: liuxue/2025/index.md
      - 计算机与软件学院:
        - 目录: liuxue/jiruan/index.md
        - MMLab-HKU PhD@CS（25届）: liuxue/jiruan/2025/cases/tianxingchen.md
        - 计软 陈铭康 - HKU MSc@CS（25届）: liuxue/jiruan/2025/cases/mingkangchen.md
        - 计软 张硕 - NUS MSc@ECE（25届）: liuxue/jiruan/2025/cases/shuozhang.md
        - 计软 李晓璐 - Maryland PhD@Stats（24届）: liuxue/jiruan/2024/cases/xiaoluli.md
        - 计软 秦言 - HKUST PhD@ECE（24届）: liuxue/jiruan/2024/cases/yanqin.md
        - 计软 王睿芃 - Upenn MS@CS（24届）: liuxue/jiruan/2024/cases/ruipengwang.md
        - 计软 忆如 - Edinburgh MS@CS（24届）: liuxue/jiruan/2024/cases/wenli.md
        - 计软 苏嘉淇 - HKU MSc@CS（24届）: liuxue/jiruan/2024/cases/jiaqisu.md
        - 计软 Anthony - HKUSTgz MSc@CS（24届）: liuxue/jiruan/2024/cases/zihaotang.md
        - 计软 快乐摸鱼生活 - HKUST MSc@TLE（24届）: liuxue/jiruan/2024/cases/yuanlan.md
        - 计软 苏政欣 – Duke@MEM（24届）: liuxue/jiruan/2024/cases/zhengxinsu.md
        - 计软 陈同学 - UMacau@DS（24届）: liuxue/jiruan/2024/cases/nuochen.md
        - 计软 彭镇灿 - Rutgers PhD@CS（22届）: liuxue/jiruan/2022/cases/zhencanpeng.md
        - 计软 詹卓欣 - SFU PhD@CS（22届）: liuxue/jiruan/2022/cases/zhuoxinzhan.md
      - 电子与信息工程学院:
        - 目录: liuxue/dianxin/index.md
      - 机电与控制学院:
        - 目录: liuxue/jidian/index.md
    - 教育与心理发展类（教育+心理+体育）: 
      - 目录: liuxue/2022/index.md # 这些都是占位的，到时候记得删掉替换，不然会报错
    - 人文与语言传播类（文院+外院+传院）: 
      - 目录: liuxue/2022/index.md
    - 政法与社会治理类（法院+马院+政管）: 
      - 目录: liuxue/2022/index.md
    - 艺术与国际交流类（艺院+国际交流+东京）:
      - 目录: liuxue/2022/index.md
    - 建筑与城市规划类（土木+城规）:
      - 目录: liuxue/2022/index.md
    - 管理与经济类（管院+经院+金科）: 
      - 管理学院:
        - 目录: liuxue/guanli/index.md
      - 经济学院:
        - 目录: liuxue/jingji/index.md
        - 经济 徐子晴 - NUS MSc@VC（23届）: liuxue/jingji/2023/cases/ziqingxu.md
      - 金融科技学院:
        - 目录: liuxue/jinke/index.md
    - 基础理学科类（数院+物光+化院+生科+高研院）: 
      - 目录: liuxue/2022/index.md
    - 医学与材料类（医学+材料）:
      - 目录: liuxue/2022/index.md
  - 保研:
    - baoyan/index.md
    - 信息与技术工程类（计软+电信+机电）: 
      # - 目录: baoyan/2025/index.md
      - 计算机与软件学院:
        - 目录: baoyan/jiruan/index.md
        - 计软 朱宇飞 - 上科大@CS（25届）: baoyan/jiruan/2025/cases/yufeizhu.md
        - 计软 钟昊天 - 浙大PhD@CS（25届）: baoyan/jiruan/2025/cases/haotianzhong.md
        - 计软 陈潇泳 - 北理工@CS（25届）: baoyan/jiruan/2025/cases/xiaoyongchen.md
        - 计软 李深艺 - 北大PhD@Matl（25届）: baoyan/jiruan/2025/cases/shenyili.md
        - 计软 蒋畅之 - 中科院PhD@Astro（25届）: baoyan/jiruan/2025/cases/changzhijiang.md
        - 计软 Mia - 东南@CS（25届）: baoyan/jiruan/2025/cases/zhentingliao.md
        - 计软 李林一 - 南开程明明组PhD@CS（25届）: baoyan/jiruan/2025/cases/linyili.md
        - 计软 宋宗硕 - 成电@CS（25届）: baoyan/jiruan/2025/cases/zhongshuosong.md
        - 计软 张豪杰 - 深大PhD@CS（25届）: baoyan/jiruan/2025/cases/haojiezhang.md
        - 计软 陈镇熙 - 中大@CS（25届）: baoyan/jiruan/2025/cases/zhenxichen.md
        - 计软 陈家豪 - 北大深圳@IC（25届）: baoyan/jiruan/2025/cases/jiahaochen.md
        - 计软 陈婉纯 - 华南理工PhD@CS（25届）: baoyan/jiruan/2025/cases/wanchunchen.md
        - 计软 王淇 - 南科大@Math（25届）: baoyan/jiruan/2025/cases/qiwang.md
        - 计软 苏梓瀚 - 清华深圳@CS（24届）: baoyan/jiruan/2024/cases/zihansu.md
        - 计软 梁霈柔 - 中科大@CS（24届）: baoyan/jiruan/2024/cases/peirouliang.md
        - 计软 汪贝琪 - 华科@CS（24届）: baoyan/jiruan/2024/cases/beiqiwang.md
        - 计软 陈耿 - 北邮@CS（24届）: baoyan/jiruan/2024/cases/gengchen.md
        - 计软 洪钊彦 - 人大信院PhD@CS（24届）: baoyan/jiruan/2024/cases/zhaoyanhong.md
        - 计软 陈俊明 - 电科@CS（24届）: baoyan/jiruan/2024/cases/junmingchen.md
        - 计软 何志浩 - 上交PhD@CS（24届）: baoyan/jiruan/2024/cases/zhihaohe.md
        - 计软 刘涛 - 南开媒体计算实验室@CS（24届）: baoyan/jiruan/2024/cases/taoliu.md
        - 计软 郭奕彤 - 清华深圳@药学（24届）: baoyan/jiruan/2024/cases/yitongguo.md
        - 计软 许宏浩 - 深大VCC优青组@CS（23届）: baoyan/jiruan/2023/cases/honghaoxu.md
        - 计软 曹弈轩 - 深大@CS（23届）: baoyan/jiruan/2023/cases/yixuancao.md
        - 计软 ywh - 厦大MAC实验室@CS（23届）: baoyan/jiruan/2023/cases/weihaoye.md
      - 电子与信息工程学院:
        - 目录: baoyan/jidian/index.md
      - 机电与控制学院:
        - 目录: baoyan/dianxin/index.md
    - 教育与心理发展类（教育+心理+体育）: 
      - 目录: liuxue/2022/index.md
    - 人文与语言传播类（文院+外院+传院）: 
      - 目录: liuxue/2022/index.md
    - 政法与社会治理类（法院+马院+政管）: 
      - 目录: liuxue/2022/index.md
    - 艺术与国际交流类（艺院+国际交流+东京）:
      - 目录: liuxue/2022/index.md
    - 建筑与城市规划类（土木+城规）:
      - 目录: liuxue/2022/index.md
    - 管理与经济类（管院+经院+金科）: 
      - 目录: liuxue/2022/index.md
    - 基础理学科类（数院+物光+化院+生科+高研院）: 
      - 目录: liuxue/2022/index.md
    - 医学与材料类（医学+材料）:
      - 目录: liuxue/2022/index.md
  - 考研:
    - kaoyan/index.md
    - 信息与技术工程类（计软+电信+机电）: 
      - 计算机与软件学院:
        - 目录: kaoyan/jiruan/index.md
        - 计软 颜治强 - 哈工深@CS（24届）: kaoyan/jiruan/2024/cases/zhiqiangyan.md
      - 电子与信息工程学院:
        - 目录: kaoyan/dianxin/index.md
      - 机电与控制学院:
        - 目录: kaoyan/jidian/index.md
    - 教育与心理发展类（教育+心理+体育）: 
      - 目录: liuxue/2022/index.md
    - 人文与语言传播类（文院+外院+传院）: 
      - 目录: liuxue/2022/index.md
    - 政法与社会治理类（法院+马院+政管）: 
      - 目录: liuxue/2022/index.md
    - 艺术与国际交流类（艺院+国际交流+东京）:
      - 目录: liuxue/2022/index.md
    - 建筑与城市规划类（土木+城规）:
      - 目录: liuxue/2022/index.md
    - 管理与经济类（管院+经院+金科）: 
      - 目录: liuxue/2022/index.md
    - 基础理学科类（数院+物光+化院+生科+高研院）: 
      - 目录: liuxue/2022/index.md
    - 医学与材料类（医学+材料）:
      - 目录: liuxue/2022/index.md
  - 就业:
    - jiuye/index.md
    - 信息与技术工程类（计软+电信+机电）: 
      # - 目录: jiuye/2026/index.md
      - 计算机与软件学院: 
        - 目录: jiuye/jiruan/index.md
        - 计软 关浩林 - Kasma实习（26届）: jiuye/jiruan/2026/cases/haolinguan.md
        - 计软 李伟力 - 量化交易（25届）: jiuye/jiruan/2025/cases/weilili.md
        - 计软 陈梓淳 - 腾讯实习转正（25届）: jiuye/jiruan/2025/cases/zichunchen.md
        - 计软 李佳乐 - 腾讯实习转正（25届）: jiuye/jiruan/2025/cases/jialeli.md
        - 计软 闪闪 - 腾讯实习（25届）: jiuye/jiruan/2025/cases/yaqinshan.md
        - 计软 叶可禾 - 腾讯实习（25届）: jiuye/jiruan/2025/cases/keheye.md
        - 计软 刘逸飞 - 腾讯、字节、深信服实习（25届）: jiuye/jiruan/2025/cases/yifeililu.md
        - 计软 debug君 - 深信服（已离职）+ 美团（21届）: jiuye/jiruan/2021/cases/zehongluo.md
      - 电子与信息工程学院:
        - 目录: jiuye/dianxin/index.md
      - 机电与控制学院:
        - 目录: jiuye/jidian/index.md
    - 教育与心理发展类（教育+心理+体育）: 
      - 目录: liuxue/2022/index.md
    - 人文与语言传播类（文院+外院+传院）: 
      - 目录: liuxue/2022/index.md
    - 政法与社会治理类（法院+马院+政管）: 
      - 目录: liuxue/2022/index.md
    - 艺术与国际交流类（艺院+国际交流+东京）:
      - 目录: liuxue/2022/index.md
    - 建筑与城市规划类（土木+城规）:
      - 目录: liuxue/2022/index.md
    - 管理与经济类（管院+经院+金科）: 
      - 目录: liuxue/2022/index.md
    - 基础理学科类（数院+物光+化院+生科+高研院）: 
      - 目录: liuxue/2022/index.md
    - 医学与材料类（医学+材料）:
      - 目录: liuxue/2022/index.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.footer
    - navigation.top
    - toc.follow
    - announce.dismiss
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: false

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized
  - add-number:
      strict_mode: False
      order: 2
  - git-authors:
      show_contribution: true
